### ISSUE TITLE
Timeout fetching account

### ISSUE THREAD

**Issue by tieppm** [Limych/ha-jq300#24]
I just bought JQ 200 and i signed up and used the app perthings normally.  Indicators displayed normally.  I installed the component via HAC.  and configure as follows:
`jq300:
  username: mi********4@gmail.com
  password: ******
  devices:
    - Kitchen
logger:
  default: info
  logs:
    custom_components.jq300: debug`

But after restart, hassio does not show error in the log. 

`Logger: custom_components.jq300
Source: custom_components/jq300/__init__.py:603
Integration: JQ-300/200/100 Indoor Air Quality Meter (documentation)
First occurred: 22:32:25 (1 occurrences)
Last logged: 22:32:25
Timeout fetching mi********4@gm**l.com device's sensors`
 
Looks like I didn't see the login to my account and can't get any data on the server.  But when I went back to the mobile app, my account was logged out.  hope you will fix this situation soon.  thank you. sorry my English very bad :(

**Comment by Limych** [comment]
Please fill-in a bug report using the template that was provided. Without this, I have not enough information to help you.

**Comment by tieppm** [comment]
Yes. Thank you

**Comment by Sysoev86** [comment]
Logger: custom_components.jq300
Source: custom_components/jq300/__init__.py:276 
Integration: JQ-300/200/100 Indoor Air Quality Meter (documentation) 
First occurred: 1:07:07 (1 occurrences) 
Last logged: 1:07:07

Error! HTTPConnectionPool(host='www.youpinyuntai.com', port=32086): Max retries exceeded with url: /ypyt-api/api/app/loginByEmail?uid=-1000&safeToken=anonymous&chr=clt&email=aleksey%40myemail.net&password=Pass&os=2 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f76a23e50>, 'Connection to www.youpinyuntai.com timed out. (connect timeout=7)'))
