### ISSUE TITLE
Issues with eCO2 vs TVOC values

### ISSUE THREAD

**Issue by frpaulsen** [Limych/ha-jq300#5]
It look like the graphs created by the eCO2 and TVOC have excatly the same shape, with a few minor exception (sampling issues?). Is there a mixup of the values that is collected from the unit?

I dont belive logs or configuration files would help you regarding this issue, but I have attached a document that shows the graphs.

[ha-jq300.docx](https://github.com/Limych/ha-jq300/files/4802689/ha-jq300.docx)

**Comment by Limych** [comment]
Chart data is taken from the cloud. My component does not calculate them (but smooths the indicators a bit to get rid of the “saw” on the charts).

A good CO2 sensor (only the sensor itself) costs $ 20 - more expensive than the whole device. Hence the conclusion: yes, this device can pretty much lie because of the cheap sensor inside.
